version: '3.8'

services:

  post_db:
    build:
      context: ./post
      dockerfile: ./db.dockerfile
    ports:
      - 127.0.0.1:5432:5432
    network_mode: host
    environment:
      POSTGRES_USER: nyx-post
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped
