# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: app.proto for package 'app'

require 'grpc'
require_relative 'app_pb'

module App
  module PostAppService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'app.PostAppService'

      rpc :PostTitle, ::App::TitleRequest, ::App::TitleReply
    end

    Stub = Service.rpc_stub_class
  end
end
