# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("app.proto", :syntax => :proto3) do
    add_message "app.TitleRequest" do
      optional :title, :string, 1
    end
    add_message "app.TitleReply" do
      optional :title, :string, 1
    end
  end
end

module App
  TitleRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("app.TitleRequest").msgclass
  TitleReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("app.TitleReply").msgclass
end
