# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: app.proto for package 'app'

require 'grpc'
require 'app_pb'

module App
  module Post
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'app.Post'

      rpc :PostHello, ::App::PostRequest, ::App::PostReply
    end

    Stub = Service.rpc_stub_class
  end
end
